### ISSUE TITLE
Do pyarea support GOES1-7 AREA projection?

### ISSUE THREAD

**Issue by ben108472** [jferencik/pyarea#1]
I find pyarea contains nav.py.
Can you briefly explain how to use this to get the latlon from GOES1-7 AREA.
Thanks.

**Comment by jferencik** [comment]
Hi. My take is you might not be able to reproject GOES 1-7 but you can give
it a shot. Try to read an area file and the class will attempt to create a
navigation object instance. That object would then have toLinEle method
wich shoukd do the reprojection.

**Comment by ben108472** [comment]
Here is the GOES-7 AREA files.
https://download.bou.class.noaa.gov/download/3429094335/001
Can you try to use these files for testing reprojection?
I still don't understand how to use navblock.
